// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel23;
lv_obj_t * ui_Label18;
lv_obj_t * ui_timeLBL;
lv_obj_t * ui_secLBL;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label2;
lv_obj_t * ui_dateLBL;
lv_obj_t * ui_dayLBL;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_batVoltage;
lv_obj_t * ui_batPercent;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Bar1;
void ui_event_Panel14(lv_event_t * e);
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Panel21;
void ui_event_Panel25(lv_event_t * e);
lv_obj_t * ui_Panel25;
void ui_event_Panel26(lv_event_t * e);
lv_obj_t * ui_Panel26;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Panel17;
// CUSTOM VARIABLES


// SCREEN: ui_setMenu
void ui_setMenu_screen_init(void);
lv_obj_t * ui_setMenu;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label6;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label7;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label12;
// CUSTOM VARIABLES


// SCREEN: ui_setTime
void ui_setTime_screen_init(void);
lv_obj_t * ui_setTime;
void ui_event_hrUp(lv_event_t * e);
lv_obj_t * ui_hrUp;
lv_obj_t * ui_Label20;
void ui_event_minUp(lv_event_t * e);
lv_obj_t * ui_minUp;
lv_obj_t * ui_Label21;
void ui_event_hrDown(lv_event_t * e);
lv_obj_t * ui_hrDown;
lv_obj_t * ui_Label22;
void ui_event_minDown(lv_event_t * e);
lv_obj_t * ui_minDown;
lv_obj_t * ui_Label23;
void ui_event_saveTime(lv_event_t * e);
lv_obj_t * ui_saveTime;
lv_obj_t * ui_Label24;
lv_obj_t * ui_setHrLBL;
lv_obj_t * ui_setMinLBL;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Panel24;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label32;
// CUSTOM VARIABLES


// SCREEN: ui_setDate
void ui_setDate_screen_init(void);
lv_obj_t * ui_setDate;
void ui_event_monthUP(lv_event_t * e);
lv_obj_t * ui_monthUP;
lv_obj_t * ui_Label4;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label25;
void ui_event_dayUp(lv_event_t * e);
lv_obj_t * ui_dayUp;
lv_obj_t * ui_Label26;
void ui_event_monthDowm(lv_event_t * e);
lv_obj_t * ui_monthDowm;
lv_obj_t * ui_Label27;
void ui_event_dayDown(lv_event_t * e);
lv_obj_t * ui_dayDown;
lv_obj_t * ui_Label28;
void ui_event_saveDate(lv_event_t * e);
lv_obj_t * ui_saveDate;
lv_obj_t * ui_Label29;
lv_obj_t * ui_setMonthLBL;
lv_obj_t * ui_setDayLBL;
void ui_event_yearUp(lv_event_t * e);
lv_obj_t * ui_yearUp;
lv_obj_t * ui_Label30;
void ui_event_yearDown(lv_event_t * e);
lv_obj_t * ui_yearDown;
lv_obj_t * ui_Label31;
lv_obj_t * ui_setYearLBL;
lv_obj_t * ui_Label34;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label33;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_1091402213[3] = {&ui_img_683590454, &ui_img_602517921, &ui_img_1415964700};
const lv_img_dsc_t * ui_imgset_1892322543[1] = {&ui_img_878922401};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
        brightMax(e);
    }
}

void ui_event_Panel14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setMenu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_setMenu_screen_init);
    }
}

void ui_event_Panel25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        callBeep(e);
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Panel26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        cngBrightness(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setTime, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_setTime_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        prepareTime(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setDate, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_setDate_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        prepareTime(e);
    }
}

void ui_event_hrUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        choseTime(e);
    }
}

void ui_event_minUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        choseTime(e);
    }
}

void ui_event_hrDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        choseTime(e);
    }
}

void ui_event_minDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        choseTime(e);
    }
}

void ui_event_saveTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        choseTime(e);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_monthUP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        choseTime(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_dayUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        choseTime(e);
    }
}

void ui_event_monthDowm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        choseTime(e);
    }
}

void ui_event_dayDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        choseTime(e);
    }
}

void ui_event_saveDate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        choseTime(e);
    }
}

void ui_event_yearUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        choseTime(e);
    }
}

void ui_event_yearDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        choseTime(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
        brightNormal(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_setMenu_screen_init();
    ui_setTime_screen_init();
    ui_setDate_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
