// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_setTime_screen_init(void)
{
    ui_setTime = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hrUp = lv_obj_create(ui_setTime);
    lv_obj_set_width(ui_hrUp, 100);
    lv_obj_set_height(ui_hrUp, 50);
    lv_obj_set_x(ui_hrUp, -65);
    lv_obj_set_y(ui_hrUp, -76);
    lv_obj_set_align(ui_hrUp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hrUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_hrUp, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hrUp, lv_color_hex(0xAEC7DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hrUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hrUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_hrUp);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "+");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minUp = lv_obj_create(ui_setTime);
    lv_obj_set_width(ui_minUp, 100);
    lv_obj_set_height(ui_minUp, 50);
    lv_obj_set_x(ui_minUp, 65);
    lv_obj_set_y(ui_minUp, -76);
    lv_obj_set_align(ui_minUp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_minUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_minUp, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_minUp, lv_color_hex(0xAEC7DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_minUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_minUp);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "+");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hrDown = lv_obj_create(ui_setTime);
    lv_obj_set_width(ui_hrDown, 100);
    lv_obj_set_height(ui_hrDown, 50);
    lv_obj_set_x(ui_hrDown, -65);
    lv_obj_set_y(ui_hrDown, 67);
    lv_obj_set_align(ui_hrDown, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hrDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_hrDown, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hrDown, lv_color_hex(0xAEC7DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hrDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hrDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_hrDown);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "-");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minDown = lv_obj_create(ui_setTime);
    lv_obj_set_width(ui_minDown, 100);
    lv_obj_set_height(ui_minDown, 50);
    lv_obj_set_x(ui_minDown, 65);
    lv_obj_set_y(ui_minDown, 67);
    lv_obj_set_align(ui_minDown, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_minDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_minDown, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_minDown, lv_color_hex(0xAEC7DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_minDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_minDown);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "-");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_saveTime = lv_obj_create(ui_setTime);
    lv_obj_set_width(ui_saveTime, 139);
    lv_obj_set_height(ui_saveTime, 50);
    lv_obj_set_x(ui_saveTime, -4);
    lv_obj_set_y(ui_saveTime, -144);
    lv_obj_set_align(ui_saveTime, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_saveTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_saveTime, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_saveTime, lv_color_hex(0xE1109F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_saveTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_saveTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_saveTime);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "SAVE");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setHrLBL = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_setHrLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setHrLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setHrLBL, -63);
    lv_obj_set_y(ui_setHrLBL, 5);
    lv_obj_set_align(ui_setHrLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setHrLBL, "25");
    lv_obj_set_style_text_font(ui_setHrLBL, &ui_font_digits, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setMinLBL = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_setMinLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setMinLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setMinLBL, 68);
    lv_obj_set_y(ui_setMinLBL, 4);
    lv_obj_set_align(ui_setMinLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setMinLBL, "25");
    lv_obj_set_style_text_font(ui_setMinLBL, &ui_font_digits, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_setTime);
    lv_obj_set_width(ui_Panel16, 8);
    lv_obj_set_height(ui_Panel16, 8);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel24 = lv_obj_create(ui_setTime);
    lv_obj_set_width(ui_Panel24, 8);
    lv_obj_set_height(ui_Panel24, 8);
    lv_obj_set_x(ui_Panel24, 0);
    lv_obj_set_y(ui_Panel24, 18);
    lv_obj_set_align(ui_Panel24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_setTime);
    lv_obj_set_width(ui_Button5, 169);
    lv_obj_set_height(ui_Button5, 58);
    lv_obj_set_x(ui_Button5, 0);
    lv_obj_set_y(ui_Button5, 149);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "HOME");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xB8C8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_hrUp, ui_event_hrUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minUp, ui_event_minUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hrDown, ui_event_hrDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minDown, ui_event_minDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_saveTime, ui_event_saveTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}
