// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void brightMax(lv_event_t * e);
void callBeep(lv_event_t * e);
void cngBrightness(lv_event_t * e);
void prepareTime(lv_event_t * e);
void choseTime(lv_event_t * e);
void brightNormal(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
