// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_setDate_screen_init(void)
{
    ui_setDate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monthUP = lv_obj_create(ui_setDate);
    lv_obj_set_width(ui_monthUP, 80);
    lv_obj_set_height(ui_monthUP, 50);
    lv_obj_set_x(ui_monthUP, -110);
    lv_obj_set_y(ui_monthUP, -76);
    lv_obj_set_align(ui_monthUP, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_monthUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_monthUP, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_monthUP, lv_color_hex(0xAEC7DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_monthUP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_monthUP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_monthUP);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "+");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_setDate);
    lv_obj_set_width(ui_Button1, 169);
    lv_obj_set_height(ui_Button1, 58);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 149);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "HOME");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xB8C8D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dayUp = lv_obj_create(ui_setDate);
    lv_obj_set_width(ui_dayUp, 80);
    lv_obj_set_height(ui_dayUp, 50);
    lv_obj_set_x(ui_dayUp, 0);
    lv_obj_set_y(ui_dayUp, -76);
    lv_obj_set_align(ui_dayUp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dayUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dayUp, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dayUp, lv_color_hex(0xAEC7DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dayUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dayUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_dayUp);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "+");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monthDowm = lv_obj_create(ui_setDate);
    lv_obj_set_width(ui_monthDowm, 80);
    lv_obj_set_height(ui_monthDowm, 50);
    lv_obj_set_x(ui_monthDowm, -110);
    lv_obj_set_y(ui_monthDowm, 67);
    lv_obj_set_align(ui_monthDowm, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_monthDowm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_monthDowm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_monthDowm, lv_color_hex(0xAEC7DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_monthDowm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_monthDowm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_monthDowm);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "-");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dayDown = lv_obj_create(ui_setDate);
    lv_obj_set_width(ui_dayDown, 80);
    lv_obj_set_height(ui_dayDown, 50);
    lv_obj_set_x(ui_dayDown, 0);
    lv_obj_set_y(ui_dayDown, 67);
    lv_obj_set_align(ui_dayDown, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dayDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dayDown, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dayDown, lv_color_hex(0xAEC7DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dayDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dayDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_dayDown);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "-");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_saveDate = lv_obj_create(ui_setDate);
    lv_obj_set_width(ui_saveDate, 139);
    lv_obj_set_height(ui_saveDate, 50);
    lv_obj_set_x(ui_saveDate, -4);
    lv_obj_set_y(ui_saveDate, -144);
    lv_obj_set_align(ui_saveDate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_saveDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_saveDate, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_saveDate, lv_color_hex(0xC10B88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_saveDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_saveDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_saveDate);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "SAVE");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setMonthLBL = lv_label_create(ui_setDate);
    lv_obj_set_width(ui_setMonthLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setMonthLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setMonthLBL, -110);
    lv_obj_set_y(ui_setMonthLBL, 12);
    lv_obj_set_align(ui_setMonthLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setMonthLBL, "25");
    lv_obj_set_style_text_font(ui_setMonthLBL, &ui_font_secs, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setDayLBL = lv_label_create(ui_setDate);
    lv_obj_set_width(ui_setDayLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setDayLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setDayLBL, 0);
    lv_obj_set_y(ui_setDayLBL, 14);
    lv_obj_set_align(ui_setDayLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setDayLBL, "25");
    lv_obj_set_style_text_font(ui_setDayLBL, &ui_font_secs, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yearUp = lv_obj_create(ui_setDate);
    lv_obj_set_width(ui_yearUp, 80);
    lv_obj_set_height(ui_yearUp, 50);
    lv_obj_set_x(ui_yearUp, 110);
    lv_obj_set_y(ui_yearUp, -76);
    lv_obj_set_align(ui_yearUp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_yearUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_yearUp, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_yearUp, lv_color_hex(0xAEC7DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_yearUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_yearUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_yearUp);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "+");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yearDown = lv_obj_create(ui_setDate);
    lv_obj_set_width(ui_yearDown, 80);
    lv_obj_set_height(ui_yearDown, 50);
    lv_obj_set_x(ui_yearDown, 110);
    lv_obj_set_y(ui_yearDown, 69);
    lv_obj_set_align(ui_yearDown, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_yearDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_yearDown, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_yearDown, lv_color_hex(0xAEC7DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_yearDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_yearDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_yearDown);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "-");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setYearLBL = lv_label_create(ui_setDate);
    lv_obj_set_width(ui_setYearLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setYearLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setYearLBL, 110);
    lv_obj_set_y(ui_setYearLBL, 17);
    lv_obj_set_align(ui_setYearLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setYearLBL, "25");
    lv_obj_set_style_text_font(ui_setYearLBL, &ui_font_secs, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_setDate);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 7);
    lv_obj_set_y(ui_Label34, -33);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, " MONTH              DAY                  YEAR      ");
    lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_monthUP, ui_event_monthUP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dayUp, ui_event_dayUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_monthDowm, ui_event_monthDowm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dayDown, ui_event_dayDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_saveDate, ui_event_saveDate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_yearUp, ui_event_yearUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_yearDown, ui_event_yearDown, LV_EVENT_ALL, NULL);

}
